# Generated by Django 4.1.7 on 2023-03-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('published', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('pages', models.IntegerField()),
                ('rating', models.FloatField(max_length=5)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.author')),
            ],
        ),
    ]
